version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: starbucks
      MYSQL_USER: admin1
      MYSQL_PASSWORD: cmpe172
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  starbucks-client:
    image: spring-starbucks-client
    platform: linux/amd64
    ports:
      - "8081:8081"
    environment:
      API_KEY: ""
      API_HOST: "kong:8000/api"
      REGISTER: "5012349"
    restart: always

  kong:
    image: kong:2.4.0
    platform: linux/amd64
    depends_on:
      - starbucks
    restart: always
    volumes:
      - ./kong.yaml:/kong.yaml
    ports:
      - "8000:8000"
      - "443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong.yaml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

  starbucks:
    image: spring-starbucks-api
    depends_on:
      - mysql
#    ports:
      #- 8080  #should be 8081?
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "admin1"
      MYSQL_PASS: "cmpe172"
      MYSQL_SCHEMA: "starbucks"
      SPRING_PROFILES_ACTIVE: "test"
    restart: always

  haproxy:
    image: eeacms/haproxy
    depends_on:
      - starbucks
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5000:8080"
      - "1936:1936"
    environment:
      HTTPCHK: "GET /ping"
      BACKENDS: "starbucks-client"
      BACKENDS_PORT: "8081"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"

#  cashier1:
#    image: spring-cashier
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/midterm
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: welcome
#    # deploy:
#    #   replicas: 2
#    depends_on:
#      - db
#    #ports:
#    #  - 9000:9090
#
#  cashier2:
#    image: spring-cashier
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/midterm
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: welcome
#    # deploy:
#    #   replicas: 2
#    depends_on:
#      - db
#    #ports:
#    #  - 9001:9090

volumes:
  db_data:
