apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-cm
data:
  kong.yaml: |
    _format_version: "1.1"

    services:
      - name: backend-service
        url: http://10.128.0.8:8080
        routes:
          - name: my-node-route
            paths:
              - /
        plugins:
          - name: key-auth

    consumers:
      - username: QA
        keyauth_credentials:
          - key: testing123